# This is a basic workflow to help you get started with Actions

name: Commit Core

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      message:
        default: Automated Commit
        description: Message for the Commit
        required: true



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  export-unpack-commit:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token": ${{ secrets.REPO_TOKEN_SECRET }}
      - uses: microsoft/powerplatform-actions/export-solution@latest
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-output-file: kon_core.zip
          solution-name: KontosoCore
      - uses: microsoft/powerplatform-actions/export-solution@latest
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-output-file: kon_core_managed.zip
          solution-name: KontosoCore
          managed: true
      - name: Clear existing solution solution-folder
        run: |
          rm -rf solutions/kon_core/src
        shell: bash
      - uses: microsoft/powerplatform-actions/unpack-solution@latest
        with:
          solution-file: kon_core.zip
          solution-folder: solutions/kon_core/src
          solution-type: Both
      - uses: EndBug/add-and-commit@v8
        with:
          message: ${{ github.event.inputs.message }}
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          token: ${{ secrets.REPO_TOKEN_SECRET }}